[connections.snowflake]
account = "GADKRQN.ESB02286"
user = "TSHINDEN21"
password = "agRdpn-Vt0fTlQ"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
